version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Insatlling NPM Packages and wget Enviorment File
      - npm install
      - npm install babel-cli cross-env --global
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
      - ls -al
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...
      - ls -al
      - find . -name 'dist'
      - ls -al dist/src
      - find . -name 'appspec.yml'
      - find . -name 'node_modules'
artifacts:
  files:
    - '**/*'
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'
